### ISSUE TITLE
Create dataset loader for health-fact

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#29] opened 2022-01-21 22:27 UTC
From https://github.com/neemakot/Health-Fact-Checking/blob/master/data/DATASHEET.md

**Comment by benjaminbeilharz** [comment] 2022-03-31 08:07
#self-assign

**Comment by hakunanatasha** [comment] 2022-04-06 16:05
Hi @benjaminbeilharz, can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**, no worries if you are not finished but intend to work on this. Please either @hakunanatasha or ping the discord admins (with @admins)

**Comment by tanmaylaud** [comment] 2022-04-21 01:15
#self-assign

**Comment by albertvillanova** [comment] 2022-04-21 15:14
I think this is a duplicate of:
- #218

CC: @hakunanatasha

**Closed** 2022-05-15 22:51 UTC
Labels: plain text, High, Fact-Verification
