### ISSUE TITLE
Create dataset loader for BioASQ Task 2020 MESINESP / MESINESP2

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#207] opened 2022-03-22 00:12 UTC
## Adding a Dataset
- **Name:** BioASQ Task 2020 MESINESP / MESINESP2
- **Description:** *None provided*
- **Task:** DOC_CLASS
- **Paper:** http://ceur-ws.org/Vol-2936/paper-11.pdf
- **Data:** https://zenodo.org/record/5602914#.YhSXJ5PMKWt
- **License:** CC BY 4.0

**Comment by jdposada** [comment] 2022-04-01 18:49
#self-assign

**Comment by jason-fries** [comment] 2022-04-07 22:10
Hi @jdposada can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by jdposada** [comment] 2022-04-08 18:10
hi @jason-fries ,

I am still working on this. Actually working with someone else. How can I give him credit as well?

**Comment by jason-fries** [comment] 2022-04-08 18:19
Thanks for the update @jdposada 
I would have the person working on the implementation add their GitHub user name to the relevant datasets.  Or is this some sort of pair programming setup you are talking about?

**Comment by hakunanatasha** [comment] 2022-04-09 21:29
@jdposada you can make a note in the PR that the script was co-authored by two people; however, the easiest would be to have 2 commit histories as @jason-fries mentioned from 2 users. We are open to whatever is easiest for you.

Looking forward to your submission :cherry_blossom:

**Comment by jdposada** [comment] 2022-04-15 02:37
Hi Guys,

I realized, too late this is a duplicate of

https://github.com/bigscience-workshop/biomedical/issues/208

The issue was closed and the code commited and accepted. Nothing more to do.

**Closed** 2022-04-17 20:26 UTC
Labels: duplicate, CC BY 4.0, Spanish, JSON
